# Generated by Django 5.2.8 on 2025-11-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='spots.spot'),
        ),
    ]
