# Generated by Django 5.2.8 on 2025-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(),
        ),
    ]
